language: ruby
cache: bundler
before_install: gem update bundler
script: bundle exec rake
rvm:
  - 2.0
  - 2.1
  - 2.3.3
  - ruby-head
  - jruby
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - redis-server
