language: ruby
install:
  - bundle install --retry=3
script: bundle exec rake
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx-2.2.6
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - redis-server
