require 'verdict/segmenters/base_segmenter'
require 'verdict/segmenters/static_segmenter'
require 'verdict/segmenters/fixed_percentage_segmenter'
require 'verdict/segmenters/random_percentage_segmenter'
require 'verdict/segmenters/rollout_segmenter'
require 'verdict/segmenters/beta_bernoulli_segmenter'
